name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["386", arm]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: GOOS=darwin GOARCH=${{ matrix.arch }} go build -v ./... -o mynewtool_${{ matrix.arch }}

    - name: Test
      run: go test -v ./...
    
    - name: package
      uses: actions/upload-artifact@v2
      with:
        name: mynewtool_${{ matrix.arch }}
        path: .
        if-no-files-found: error
